readhex: readFileAsHex.cpp
	g++ readFileAsHex.cpp -o readhex.out && ./readhex.out
writehex: writeHexToFile.cpp
	g++ writeHexToFile.cpp -o writehex.out && ./writehex.out
clean:
	rm -f *.o *.obj *.exe *.out
